const express = require('express')
const {authMiddleware} = require('../middlewares/authMiddleware')
const { signUp, signIn, getMe } = require('../controllers/authController')
const authRouter = express.Router()
authRouter.get("/auth/signup",(req,res)=>{res.send('/v1/auth/signup')})
authRouter.post("/auth/signup",signUp)
authRouter.get("/auth/signin",(req,res)=>{res.send('/v1/auth/signup')})   
authRouter.post("/auth/signin",signIn)   
authRouter.get("/auth/me",authMiddleware, getMe)   
module.exports = {authRouter};